Repository DaluS/GEMMES, pull requests merged in 2021-07, with the labels that each got.

#16 [#011] Second try for automated unit tests using GA
  .github/workflows/basic_workflow.yml
  requirements.txt
  tests/tests01.py
Labels: enhancement

#18 Parameters + Gregoire protomodel
  ClassesGoodwin.py
  Main.py
  Parameters.py
  README.md
  VariableDictionnary.py
  _def_parameters.py
  _def_variables.py
  _utils.py
  plots.py
Labels: bug, enhancement, help wanted

#23 [#006] Separate numerical parameters
  _class.py
Labels: enhancement

#24 Fusion between _def_parameters and VariableDictionnary.py + more advanced method
  _class.py
  _class_checks.py
  _def_parameters.py
Labels: enhancement

#52 [#051] File renamed, all dependencies checked
  Cockpit.py
  _core.py
  tests/test_01_Solver.py
Labels: enhancement

#54 Issue053 intermediary initial step in reset
  _core.py
  utilities/_class_utility.py
Labels: enhancement

#57 Issue055 additional solvers
  _core.py
  models/_model_G_Reduced.py
  tests/test_01_Solver.py
  utilities/_class_checks.py
  utilities/_solvers.py
Labels: enhancement

#62 Issue003 output data saving
  _core.py
  output/__init__.py
  tests/output/__init__.py
  tests/test_01_Solver.py
  utilities/_class_checks.py
  utilities/_class_utility.py
  utilities/_saveload.py
Labels: enhancement

#65 Issue064 first non regression
  _core.py
  tests/output_ref/Output_G-Reduced_eRK2-scipy_11_DV226270_20210723-122907.npz
  tests/output_ref/Output_G-Reduced_eRK4-homemade_10_DV226270_20210723-122907.npz
  tests/output_ref/Output_G-Reduced_eRK4-scipy_12_DV226270_20210723-122907.npz
  tests/output_ref/Output_G-Reduced_eRK8-scipy_13_DV226270_20210723-122907.npz
  tests/output_ref/Output_GK_eRK2-scipy_1_DV226270_20210723-122907.npz
  tests/output_ref/Output_GK_eRK4-homemade_0_DV226270_20210723-122907.npz
  tests/output_ref/Output_GK_eRK4-scipy_2_DV226270_20210723-122907.npz
  tests/output_ref/Output_GK_eRK8-scipy_3_DV226270_20210723-122907.npz
  tests/output_ref/__init__.py
  tests/output_temp/__init__.py
  tests/test_01_Solver.py
  utilities/_class_checks.py
  utilities/_class_utility.py
  utilities/_saveload.py
Labels: enhancement, unit tests
